# Generated by Django 2.2.2 on 2019-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_object', models.CharField(max_length=100)),
                ('card_action', models.CharField(max_length=100)),
                ('card_movie', models.CharField(max_length=100)),
                ('card_all', models.CharField(max_length=100)),
            ],
        ),
    ]
