# Generated by Django 2.2.6 on 2019-11-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary', '0002_cards1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
