# Generated by Django 2.2.6 on 2019-11-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary', '0003_delete_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards1',
            new_name='Cards',
        ),
    ]
