# Generated by Django 2.2.2 on 2020-05-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictionary', '0004_auto_20191124_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
