# Generated by Django 2.2.2 on 2020-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pictionary', '0005_delete_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_object', models.CharField(max_length=100)),
                ('card_action', models.CharField(max_length=100)),
                ('card_food', models.CharField(max_length=100)),
                ('card_allplay', models.CharField(max_length=100)),
            ],
        ),
    ]
